routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-message',function(){

	$response = \App\Helpers\MessageHelper::send('923222093633','کیوں رے زیادہ چربی چڑھی ہے کیا');

	dd($response);

});



Auth::routes(['verify' => true]);
/*

Route::get('/cruest/{name}', 'CruestController@index');



Route::get('/mailable', function () {
 $invoice = App\Invoice::find(1);
 return new App\Mail\InvoicePaid($invoice);
});


Route::middleware(['auth','verified'])->group(function(){

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('user/profile','UserController@profile')->name('user.profile');
	Route::get('role/permissions/{id}', 'RoleController@permission')->name('role.permission');
	Route::post('role/permissions', 'RoleController@savePermissions')->name('save.role.permission');
	Route::resource('role', 'RoleController');
	Route::resource('permission', 'PermissionController');
	Route::resource('brands', 'BrandController');
	Route::resource('banners', 'BannerController');
	Route::resource('brands', 'BrandController');
	Route::resource('categories', 'CategoryController');
	Route::resource('orders', 'OrderController');
	Route::resource('pages', 'PageController');
	Route::resource('paymentmethods', 'PaymentmethodController');
	Route::resource('products', 'ProductController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('shippingmethods', 'ShippingmethodController');
	Route::resource('stores', 'StoreController');
	Route::resource('users', 'UserController');
});

*/

app/Models/Permission.php
<?php

namespace App\Models;

class Permission extends BaseModel
{
    
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\Permission\GetAllPermissionsRequest;
use App\Http\Requests\Permission\GetPermissionRequest;
use App\Http\Requests\Permission\CreatePermissionRequest;
use App\Http\Requests\Permission\UpdatePermissionRequest;
use App\Http\Requests\Permission\DeletePermissionRequest;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GetAllPermissionsRequest $request)
    {
        $response = $request->handle();

        return response()->json($response);
        // if(\Request::wantsJson()) { 
        // } else {
        //     return view('permission.index',[ 'permissions' => $response]);
        // }  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show(GetPermissionRequest $request,$id)
    {
        $request->id = $id;

        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return view('permission.form', ['permission' => $response, 'route' => route('permissions.store'), 'edit' => false ] );
        // }        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePermissionRequest $request)
    {
        $response = $request->handle();

        return response()->json($response);
        // if(\Request::wantsJson()) { 
        // } else {
        //     return redirect()->route('permissions.index');
        // }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,GetPermissionRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();

        return response()->json($response);
        // if(\Request::wantsJson()) { 
        // } else {
        //     return view('permission.form', ['permission' => $response, 'route' => route('permissions.update',['id' => $request->id ]), 'edit' => true ] );
        // }        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePermissionRequest $request, $id)
    {
        $request->id = $id;
        
        $response = $request->handle();

        return response()->json($response);
        // if(\Request::wantsJson()) { 
        // } else {
        //     return redirect()->route('permissions.index');
        // }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,DeletePermissionRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return redirect()->route('permissions.index');
        // }
    }  
}

resources/views/permission/form.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="mt-4">{{ __('permission.permissions') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item">{{ __('permission.permissions') }}</li>
        @if($edit)
        <li class="breadcrumb-item active">{{ __('permission.edit') }}</li>
        @else
        <li class="breadcrumb-item active">{{ __('permission.add') }}</li>
        @endif          
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            Fields with * are required
        </div>
    </div>
          
    <div class="card mb-4">
        <form method="POST" action="{{ $route }}" class="needs-validation" >
            @csrf

            @if($edit)
                @method('PUT')
            @endif            
            <div class="card-header d-flex align-items-center justify-content-between ">
                @if($edit)
                <span>{{ __('permission.edit') }} {{ __('permission.permission') }}</span>
                @else
                <span>{{ __('permission.add') }} {{ __('permission.permission') }}</span>
                @endif                 
                
                <a href="{{ route('permissions.index') }}" class="btn btn-primary">{{ __('permission.back') }}</a>
                @can('view-permissions')
                @endcan
            </div>
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="customer-name">{{ __('permission.name') }} <span class="text-danger">*</span></label>
                        <input value="{{ old('name',$permission->name) }}" name="name" placeholder="{{ __('permission.name') }}" id="customer-name" type="text" class="form-control  @error('name') is-invalid @enderror " required >
                        <small class="form-text text-muted">Enter permission name.</small>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-md-6">
                        <label for="customer-title">{{ __('permission.title') }} <span class="text-danger">*</span> </label>
                        <input value="{{ old('title',$permission->title) }}" name="title" placeholder="{{ __('permission.title') }}" id="customer-title" type="text" class="form-control  @error('title') is-invalid @enderror " required >
                        <small class="form-text text-muted">Enter a valid title.</small>
                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-info">Reset</button>
                <a href="{{ route('permissions.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
<script>
  $(document).ready(function() {
       
   });
</script>
  
@endsection

resources/views/permission/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="mt-4">{{ __('permission.permissions') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active">{{ __('permission.permissions') }}</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between ">
        	<span>{{ __('permission.all') }} {{ __('permission.permissions') }}</span>
			@can('add-permission')
			<a href="{{ route('permissions.create') }}" class="btn btn-primary">{{ __('permission.add') }}</a>
			@endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
				<table class="table table-bordered dataTable" id="dataTable">
				<thead>
					    <tr>
					        <th>{{ __('permission.name') }}</th>
					        <th>{{ __('permission.title') }}</th>
					        <th>{{ __('permission.actions') }}</th>
					    </tr>
					</thead>
					<tbody>
						@foreach($permissions as $permission)
					    <tr>
					        <td>{{ $permission->name }}</td>
					        <td>{{ $permission->title }}</td>
					        <td>
					        	<a href="{{ route('permissions.edit',[ 'permission' => $permission->id ]) }}">{{ __('permission.edit') }}</a>
					        	<!-- <a onclick="deletePermission({{ $permission->id }})" href="#">{{ __('permission.delete') }}</a> -->
					        </td>
					    </tr>
					    @endforeach
					</tbody>
					<tfoot>
					    <tr>
					        <th>{{ __('permission.name') }}</th>
					        <th>{{ __('permission.title') }}</th>
					        <th>{{ __('permission.actions') }}</th>
					    </tr>
					</tfoot>
				</table>

				<form id="delete-form" method="POST" style="display:none">
				    @method('DELETE')
				    @csrf
				    <button type="submit">Delete Banner</button>
				</form>
        	</div>
        </div>
    </div>
</div>

@endsection

@section('scripts')

<script type="text/javascript">
	$(document).ready(function(){

	});
</script>
@endsection