routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-message',function(){

	$response = \App\Helpers\MessageHelper::send('923222093633','کیوں رے زیادہ چربی چڑھی ہے کیا');

	dd($response);

});



Auth::routes(['verify' => true]);
/*

Route::get('/cruest/{name}', 'CruestController@index');



Route::get('/mailable', function () {
 $invoice = App\Invoice::find(1);
 return new App\Mail\InvoicePaid($invoice);
});


Route::middleware(['auth','verified'])->group(function(){

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('user/profile','UserController@profile')->name('user.profile');
	Route::get('role/permissions/{id}', 'RoleController@permission')->name('role.permission');
	Route::post('role/permissions', 'RoleController@savePermissions')->name('save.role.permission');
	Route::resource('role', 'RoleController');
	Route::resource('permission', 'PermissionController');
	Route::resource('brands', 'BrandController');
	Route::resource('banners', 'BannerController');
	Route::resource('brands', 'BrandController');
	Route::resource('categories', 'CategoryController');
	Route::resource('orders', 'OrderController');
	Route::resource('pages', 'PageController');
	Route::resource('paymentmethods', 'PaymentmethodController');
	Route::resource('products', 'ProductController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('shippingmethods', 'ShippingmethodController');
	Route::resource('stores', 'StoreController');
	Route::resource('users', 'UserController');
});

*/

resources/views/partials/footer.blade.php
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2020</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/head.blade.php
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link href="{{ asset('assets/css/styles.css') }}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
</head>

resources/views/partials/navigation.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="index.html">Eazyshop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form method="post" action="{{ route('logout') }}" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" id="logout-form">
        @csrf
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ Auth::user()->name }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Profile</a>
                <a class="dropdown-item" href="#">Settings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="javascript:;" onclick="$('#logout-form').submit()">Logout</a>
            </div>
        </li>
    </ul>
</nav>

resources/views/partials/scripts.blade.php
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('assets/js/scripts.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('assets/demo/chart-area-demo.js') }}"></script>
<script src="{{ asset('assets/demo/chart-bar-demo.js') }}"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('assets/demo/datatables-demo.js') }}"></script>

resources/views/partials/sidebar.blade.php
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <a class="nav-link" href="index.html">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>
            <div class="sb-sidenav-menu-heading">Operations</div>
            <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-shopping-cart"></i></div>
                Orders
            </a>   
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-chart-bar"></i></div>
                Reports
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
         
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="{{ route('permissions.index') }}">Sales Report</a>
                    <a class="nav-link" href="{{ route('roles.index') }}">Stock Report</a>
                    <a class="nav-link" href="{{ route('users.index') }}">Peak Time Report</a>
                    <a class="nav-link" href="{{ route('users.index') }}">User Report</a>
                </nav>
            </div> 
            <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                Customers
            </a>   
            <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-tag"></i></div>
                Promotions
            </a>
            <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-envelope-open-text"></i></div>
                Newsletter Subscriptions
            </a>
            <div class="sb-sidenav-menu-heading">Setup</div>
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts1" aria-expanded="false" aria-controls="collapseLayouts1">
                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                Catalog
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts1" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="{{ route('users.index') }}"> Attributes</a>
                    <a class="nav-link" href="{{ route('permissions.index') }}"> Brand</a>
                    <a class="nav-link" href="{{ route('roles.index') }}">Category</a>
                    <a class="nav-link" href="{{ route('users.index') }}">Product</a>
                </nav>
            </div>   
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts2" aria-expanded="false" aria-controls="collapseLayouts2">
                <div class="sb-nav-link-icon"><i class="fas fa-desktop"></i></div>
                CMS
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts2" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="{{ route('users.index') }}">Banners</a>
                    <a class="nav-link" href="{{ route('permissions.index') }}">Page</a>
                    <a class="nav-link" href="{{ route('roles.index') }}">Payment Methods</a>
                    <a class="nav-link" href="{{ route('users.index') }}">Shipping Methods</a>
                </nav>
            </div>
            <a class="nav-link" href="index.html">
                <div class="sb-nav-link-icon"><i class="fas fa-store"></i></div>
                Store
            </a> 
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts3" aria-expanded="false" aria-controls="collapseLayouts3">
                <div class="sb-nav-link-icon"><i class="fas fa-users-cog"></i></div>
                User Management
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts3" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="{{ route('permissions.index') }}">Permissions</a>
                    <a class="nav-link" href="{{ route('roles.index') }}">Roles</a>
                    <a class="nav-link" href="{{ route('users.index') }}">Users</a>
                </nav>
            </div>
          <!--   <a class="nav-link" href="index.html">
                <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
                Settings
            </a>   -->
        </div>
    </div>
    <!-- <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        {{ Auth::user()->name }}
    </div> -->
</nav>