routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-message',function(){

	$response = \App\Helpers\MessageHelper::send('923222093633','کیوں رے زیادہ چربی چڑھی ہے کیا');

	dd($response);

});



Auth::routes(['verify' => true]);
/*

Route::get('/cruest/{name}', 'CruestController@index');



Route::get('/mailable', function () {
 $invoice = App\Invoice::find(1);
 return new App\Mail\InvoicePaid($invoice);
});


Route::middleware(['auth','verified'])->group(function(){

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('user/profile','UserController@profile')->name('user.profile');
	Route::get('role/permissions/{id}', 'RoleController@permission')->name('role.permission');
	Route::post('role/permissions', 'RoleController@savePermissions')->name('save.role.permission');
	Route::resource('role', 'RoleController');
	Route::resource('permission', 'PermissionController');
	Route::resource('brands', 'BrandController');
	Route::resource('banners', 'BannerController');
	Route::resource('brands', 'BrandController');
	Route::resource('categories', 'CategoryController');
	Route::resource('orders', 'OrderController');
	Route::resource('pages', 'PageController');
	Route::resource('paymentmethods', 'PaymentmethodController');
	Route::resource('products', 'ProductController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('shippingmethods', 'ShippingmethodController');
	Route::resource('stores', 'StoreController');
	Route::resource('users', 'UserController');
});

*/

app/Models/Role.php
<?php

namespace App\Models;

class Role extends BaseModel
{
    public $table = 'roles';
    protected $guarded = ['id'];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\Role\GetAllRolesRequest;
use App\Http\Requests\Role\GetRoleRequest;
use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Http\Requests\Role\DeleteRoleRequest;
use App\Http\Requests\Role\SavePermissionsRequest;
use App\Http\Requests\Permission\GetAllPermissionsRequest;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GetAllRolesRequest $request)
    {
        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return view('role.index',['roles' => $response]);
        // }  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show(GetRoleRequest $request,$id)
    {
        $request->id = $id;

        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return view('role.form', ['role' => $response, 'route' => route('roles.store'), 'edit' => false ] );
        // }        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request)
    {
        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return redirect()->route('roles.index');
        // }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,GetRoleRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return view('role.form', ['role' => $response, 'route' => route('roles.update',['role' => $request->id ]), 'edit' => true ] );
        // }        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, $id)
    {
        $request->id = $id;
        
        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return redirect()->route('roles.index');
        // }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,DeleteRoleRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();
        return response()->json($response);

        // if(\Request::wantsJson()) { 
        // } else {
        //     return redirect()->route('roles.index');
        // }
    }  

    public function permission($id)
    {
        $request = new GetRoleRequest();

        $request->id = $id;

        $response = $request->handle();        

        $request = new GetAllPermissionsRequest();

        $permissions = $request->handle();

        return view('role.permission',[ 'role' => $response, 'permissions' => $permissions ]);
    }

    public function savePermissions(SavePermissionsRequest $request)
    {
        $response = $request->handle();        

        return redirect()->route('role.index');
    }     
}

resources/views/role/form.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="mt-4">{{ __('role.roles') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item">{{ __('role.roles') }}</li>
        @if($edit)
        <li class="breadcrumb-item active">{{ __('role.edit') }}</li>
        @else
        <li class="breadcrumb-item active">{{ __('role.add') }}</li>
        @endif          
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            Fields with * are required
        </div>
    </div>
          
    <div class="card mb-4">
        <form method="POST" action="{{ $route }}" class="needs-validation" >
            @csrf

            @if($edit)
                @method('PUT')
            @endif            
            <div class="card-header d-flex align-items-center justify-content-between ">
                @if($edit)
                <span>{{ __('role.edit') }} {{ __('role.role') }}</span>
                @else
                <span>{{ __('role.add') }} {{ __('role.role') }}</span>
                @endif                 
                
                <a href="{{ route('roles.index') }}" class="btn btn-primary">{{ __('role.back') }}</a>
                @can('view-roles')
                @endcan
            </div>
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="customer-name">{{ __('role.name') }} <span class="text-danger">*</span></label>
                        <input value="{{ old('name',$role->name) }}" name="name" placeholder="{{ __('role.name') }}" id="customer-name" type="text" class="form-control  @error('name') is-invalid @enderror " required >
                        <small class="form-text text-muted">Enter role name.</small>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-md-6">
                        <label for="customer-title">{{ __('role.title') }} <span class="text-danger">*</span> </label>
                        <input value="{{ old('title',$role->title) }}" name="title" placeholder="{{ __('role.title') }}" id="customer-title" type="text" class="form-control  @error('title') is-invalid @enderror " required >
                        <small class="form-text text-muted">Enter a valid title.</small>
                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-info">Reset</button>
                <a href="{{ route('roles.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
<script>
  $(document).ready(function() {
       
   });
</script>
  
@endsection

resources/views/role/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <h1 class="mt-4">{{ __('role.roles') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">{{ __('role.roles') }}</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between ">
        	<span>{{ __('role.all') }} {{ __('role.roles') }}</span>
			<a href="{{ route('roles.create') }}" class="btn btn-primary">{{ __('role.add') }}</a>
			@can('add-role')
			@endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
				<table class="table table-bordered dataTable" id="dataTable">
					<thead>
					    <tr>
					        <th>{{ __('role.name') }}</th>
					        <th>{{ __('role.title') }}</th>
					        <th>{{ __('role.users') }}</th>
					        <th>{{ __('role.permissions') }}</th>
					        <th>{{ __('role.actions') }}</th>
					    </tr>
					</thead>
					<tbody>
						@foreach($roles as $role)
					    <tr>
					        <td>{{ $role->name }}</td>
					        <td>{{ $role->title }}</td>
					        <td>{{ \App\Models\User::whereIs($role->name)->count() }}</td>
					        <td><a href="{{ route('role.permission',['id' => $role->id ]) }}">{{ __('role.permissions') }}</a></td>
					        <td>
					        	@can('edit-role')
					        	<a href="{{ route('role.edit',[ 'role' => $role->id ]) }}">{{ __('role.edit') }}</a>
								@endcan
								@can('delete-role')
					        	<a onclick="deleteRole({{ $role->id }})" href="#">{{ __('role.delete') }}</a>
								@endcan
					        </td>
					    </tr>
					    @endforeach
					</tbody>
					<tfoot>
					    <tr>
					        <th>{{ __('role.name') }}</th>
					        <th>{{ __('role.title') }}</th>
					        <th>{{ __('role.users') }}</th>
					        <th>{{ __('role.permissions') }}</th>
					        <th>{{ __('role.actions') }}</th>
					    </tr>
					</tfoot>
				</table>

				<form id="delete-form" method="POST" style="display:none">
				    @method('DELETE')
				    @csrf
				    <button type="submit">Delete Role</button>
				</form>                
        	</div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script type="text/javascript">
	function deleteRole(id){
		let confirmBox = confirm('{{ __("role.delete_message") }}');

		if(confirmBox){
			let path = `{{ url('roles/${id}') }}`;
			$('#delete-form').attr('action',path);
			$('#delete-form').submit();
		}
	}
</script>
@endsection

resources/views/role/permission.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="mt-4">{{ __('role.roles') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item">{{ __('role.roles') }}</li>
        <li class="breadcrumb-item active">{{ __('role.permissions') }}</li>
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            {{ $role->title }}
        </div>
    </div>
    <div class="card mb-4">
        <form method="POST" action="{{ route('save.role.permission') }}" >
            <div class="card-header d-flex align-items-center justify-content-between ">
                <span>{{ __('role.all') }} {{ __('role.roles') }}</span>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @csrf
                    <input type="hidden" value="{{ $role->name }}" name="role">

                    @php
                        $assigned_permissions = $role->getAbilities()->pluck('name')->toArray();
                    @endphp

                    <table class="table table-bordered " id="">
                        <thead>
                            <tr>
                                <th>
                                  <label>
                                    <input type="checkbox" class="permissions-all" />
                                    <span>{{ __('role.all') }}</span>
                                  </label>
                                </th>
                                <th>{{ __('role.title') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($permissions as $permission)
                            <tr>
                                <td>
                                  <label>
                                    <input 
                                        type="checkbox" 
                                        class="permission" 
                                        name="permission[]" 
                                        value="{{ $permission->name }}"
                                        id="permission-{{ $loop->index }}"
                                        {{ in_array($permission->name,$assigned_permissions) ? 'checked' : '' }}
                                     />
                                    <span>&nbsp;</span>
                                  </label>
                                </td>
                                <td><label for="permission-{{ $loop->index }}">{{ $permission->title }}</label></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer text-right">
                <button class="btn btn-primary " type="submit" name="action">
                    {{ __('role.submit') }}
                </button>
            </div>
        </form>              
    </div>
</div>


@endsection

@section('scripts')
<script>
  $(document).ready(function() {
       $('.permissions-all').change(function(){
            if($(this).is(':checked')){
                $('.permission').prop('checked',true).trigger('change');
            }else{
                $('.permission').prop('checked',false).trigger('change');
            }
       })
   });
</script>
  
@endsection