routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/send-message',function(){

	$response = \App\Helpers\MessageHelper::send('923222093633','کیوں رے زیادہ چربی چڑھی ہے کیا');

	dd($response);

});



Auth::routes(['verify' => true]);
/*

Route::get('/cruest/{name}', 'CruestController@index');



Route::get('/mailable', function () {
 $invoice = App\Invoice::find(1);
 return new App\Mail\InvoicePaid($invoice);
});


Route::middleware(['auth','verified'])->group(function(){

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('user/profile','UserController@profile')->name('user.profile');
	Route::get('role/permissions/{id}', 'RoleController@permission')->name('role.permission');
	Route::post('role/permissions', 'RoleController@savePermissions')->name('save.role.permission');
	Route::resource('role', 'RoleController');
	Route::resource('permission', 'PermissionController');
	Route::resource('brands', 'BrandController');
	Route::resource('banners', 'BannerController');
	Route::resource('brands', 'BrandController');
	Route::resource('categories', 'CategoryController');
	Route::resource('orders', 'OrderController');
	Route::resource('pages', 'PageController');
	Route::resource('paymentmethods', 'PaymentmethodController');
	Route::resource('products', 'ProductController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('shippingmethods', 'ShippingmethodController');
	Route::resource('stores', 'StoreController');
	Route::resource('users', 'UserController');
});

*/

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Silber\Bouncer\Database\HasRolesAndAbilities;


class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, Notifiable, HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //never update

    // public function setEmailAttribute($value)
    // {
    //     if ($this->email) {
    //         return;
    //     }

    //     $this->attributes['email'] = $value;
    // }

    public function getEmailVerifiedAtAttribute($value){
        return is_null($value) ? __('user.no') : __('user.yes');
    }    

    protected static function booted()
    {
        //static::observe(UserObserver::class);
    }
   
}

app/Models/UserType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    public $table = 'user_type';
    protected $guarded = ['id'];
    public $timestamps = false;
     
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\User\GetAllUsersRequest;
use App\Http\Requests\User\GetUserRequest;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Http\Requests\User\DeleteUserRequest;

use App\Http\Requests\Role\GetAllRolesRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GetAllUsersRequest $request)
    {
        $response = $request->handle();

        return response()->json($response); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(GetUserRequest $request)
    {
        $request->id = 0;

        $response = $request->handle();

        $request = new GetAllRolesRequest();

        $roles = $request->handle();

        return response()->json($response);      
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $response = $request->handle();

        return response()->json($response);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,GetUserRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();

        $request = new GetAllRolesRequest();

        $roles = $request->handle();        

        return response()->json($response);      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $request->id = $id;
        
        $response = $request->handle();

        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,DeleteUserRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();

        return response()->json($response);
    }  
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Requests\User\GetAllUsersRequest;
use App\Http\Requests\User\GetUserRequest;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Http\Requests\User\DeleteUserRequest;

use App\Http\Requests\Role\GetAllRolesRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GetAllUsersRequest $request)
    {
        $response = $request->handle();

        if(\Request::wantsJson()) { 
            return response()->json($response);
        } else {
            return view('user.index',[ 'users' => $response]);
        }  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(GetUserRequest $request)
    {
        $request->id = 0;

        $response = $request->handle();

        $request = new GetAllRolesRequest();

        $roles = $request->handle();

        if(\Request::wantsJson()) { 
            return response()->json($response);
        } else {
            return view('user.form', ['user' => $response, 'route' => route('users.store'), 'edit' => false , 'roles' => $roles ] );
        }        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $response = $request->handle();

        if(\Request::wantsJson()) { 
            return response()->json($response);
        } else {
            return redirect()->route('users.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,GetUserRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();

        $request = new GetAllRolesRequest();

        $roles = $request->handle();        

        if(\Request::wantsJson()) { 
            return response()->json($response);
        } else {
            return view('user.form', ['user' => $response, 'route' => route('users.update',['user' => $id ]), 'edit' => true, 'roles' => $roles ] );
        }        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $request->id = $id;
        
        $response = $request->handle();

        if(\Request::wantsJson()) { 
            return response()->json($response);
        } else {
            return redirect()->route('users.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,DeleteUserRequest $request)
    {
        $request->id = $id;

        $response = $request->handle();

        if(\Request::wantsJson()) { 
            return response()->json($response);
        } else {
            return redirect()->route('users.index');
        }
    }  
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('content')


<div class="container-fluid">
    <h1 class="mt-4">{{ __('user.users') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item">{{ __('user.users') }}</li>
        @if($edit)
        <li class="breadcrumb-item active">{{ __('user.edit') }}</li>
        @else
        <li class="breadcrumb-item active">{{ __('user.add') }}</li>
        @endif          
    </ol>
    <div class="card mb-4">
        <div class="card-body">
            Fields with * are required

        </div>
    </div>
          
    <div class="card mb-4">
        <form method="POST" action="{{ $route }}" class="needs-validation" >
            @csrf

            @if($edit)
                @method('PUT')
            @endif            
            <div class="card-header d-flex align-items-center justify-content-between ">
                @if($edit)
                <span>{{ __('user.edit') }} {{ __('user.user') }}</span>
                @else
                <span>{{ __('user.add') }} {{ __('user.user') }}</span>
                @endif                 
                
                <a href="{{ route('users.index') }}" class="btn btn-primary">{{ __('user.back') }}</a>
                @can('view-users')
                @endcan
            </div>
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="customer-name">{{ __('user.name') }} <span class="text-danger">*</span></label>
                        <input value="{{ old('name',$user->name) }}" name="name" placeholder="{{ __('user.name') }}" id="customer-name" type="text" class="form-control  @error('email') is-invalid @enderror " required >
                        <small class="form-text text-muted">Enter user name.</small>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-md-6">
                        <label for="customer-email">{{ __('user.email') }} </label>
                        <input value="{{ old('email',$user->email) }}" name="email" placeholder="{{ __('user.email') }}" id="customer-email" type="text" class="form-control  @error('email') is-invalid @enderror " @if($edit) readonly @endif >
                        <small class="form-text text-muted">Enter a valid email address.</small>
                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>                    
                    <div class="form-group col-md-6">
                        <label for="state">{{ __('user.role') }} <span class="text-danger">*</span></label>
                        <select name="role" class="form-control @error('role') is-invalid @enderror" required="">
                            <option value="" selected="">{{ __('user.select') }}</option>
                            @foreach($roles as $role)

                                @if($edit)
                                    <option value="{{ $role->id }}" {{ $role->name == $user->getRoles()->first() ? 'selected' : '' }} >
                                        {{ $role->title }}
                                    </option>                                            
                                @else
                                    <option value="{{ $role->id }}" >
                                        {{ $role->title }}
                                    </option>
                                @endif                                            

                            @endforeach
                        </select>
                        <small class="form-text text-muted">Please select a role</small>
                        @error('role')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror                        
                    </div>  
                    <div class="form-group col-md-6">
                        <label for="customer-password">{{ __('user.password') }}</label>
                        <div class="input-group mb-2">
                            <input value="{{ old('password') }}" name="password" placeholder="{{ __('user.password') }}" id="customer-password" type="password" class="form-control  @error('password') is-invalid @enderror " >
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <i class="fas fa-eye" id="password-toggle" ></i>
                                </div>
                            </div>
                        </div>
                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                        <small class="form-text text-muted">Password must be 8-20 characters long, contain letters and numbers only.</small>
                    </div>
                </div>
                @php
                    $user_original = $user->getRawOriginal();
                    $email_verified_at = isset($user_original['email_verified_at']) ? $user_original['email_verified_at'] : null;
                @endphp
                <div class="form-group">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" name="email_verified" id="email-verified" {{ !is_null($email_verified_at)? 'checked' : '' }} >
                        <label class="form-check-label" for="email-verified">Email Verified</label>
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-info">Reset</button>
                <a href="{{ route('users.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>


@endsection

@section('scripts')
<script type="text/javascript" >
  $(document).ready(function() {
       
   });
  $(function(){
    $('#password-toggle').click(function(){
        let type = $('#customer-password').attr('type');

        if(type == 'text'){
            $('#customer-password').attr('type','password')
        }else{
            $('#customer-password').attr('type','text')
        }
    })
  })
</script>
  
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <h1 class="mt-4">{{ __('user.users') }}</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">{{ __('user.users') }}</li>
    </ol>
<!--     <div class="card mb-4">
        <div class="card-body">
            DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the
            <a target="_blank" href="https://datatables.net/">official DataTables documentation</a>
            .
        </div>
    </div> -->
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between ">
        	<span>{{ __('user.all_users') }}</span>
			@can('add-user')
			<a href="{{ route('users.create') }}" class="btn btn-primary">{{ __('user.add') }}</a>
			@endcan
        </div>
        <div class="card-body">
            <div class="table-responsive">
				<table class="table table-bordered dataTable" id="dataTable">
					<thead>
					    <tr>
					        <th>{{ __('user.name') }}</th>
					        <th>{{ __('user.email') }}</th>
					        <th>{{ __('user.email_verified') }}</th>
					        <th>{{ __('user.role') }}</th>
					        <th>{{ __('user.actions') }}</th>
					    </tr>
					</thead>
					<tbody>
						@foreach($users as $user)
					    <tr>
					        <td>{{ $user->name }}</td>
					        <td>{{ $user->email }}</td>
					        <td>{{ $user->email_verified_at }}</td>
					        <td>{{ $user->getRoles()->first() }}</td>
					        <td>
					        	@can('edit-role')
					        		<a href="{{ route('users.edit',[ 'user' => $user->id ]) }}">{{ __('user.edit') }}</a>
								@endcan
								@can('delete-role')
						        	<a onclick="deleteUser({{ $user->id }})" href="#">{{ __('user.delete') }}</a>
								@endcan

					        </td>
					    </tr>
					    @endforeach
					</tbody>
					<tfoot>
					    <tr>
					        <th>{{ __('user.name') }}</th>
					        <th>{{ __('user.email') }}</th>
					        <th>{{ __('user.email_verified') }}</th>
					        <th>{{ __('user.role') }}</th>
					        <th>{{ __('user.actions') }}</th>
					    </tr>
					</tfoot>
				</table>

				<form id="delete-form" method="POST" style="display:none">
				    @method('DELETE')
				    @csrf
				    <button type="submit">Delete Banner</button>
				</form>                
        	</div>
        </div>
    </div>
</div>

@endsection

@section('scripts')

<style type="text/css">
	div.dt-buttons {
		margin-bottom:20px;
	}

</style>
<script type="text/javascript">
	function deleteUser(id){
		let confirmBox = confirm('{{ __("user.delete_message") }}');

		if(confirmBox){
			let path = `{{ url('users/${id}') }}`;
			$('#delete-form').attr('action',path);
			$('#delete-form').submit();
		}
	}
	
</script>
@endsection

resources/views/user/profile.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="pt-3 pb-1" id="breadcrumbs-wrapper">
    <!-- Search for small screen-->
    <div class="container">
        <div class="row">
            <div class="col s12 m6 l6">
                <h5 class="breadcrumbs-title mt-0 mb-0"><span>{{ __('profile.profile') }}</span></h5>
            </div>
            <div class="col s12 m6 l6 right-align-md">
                <ol class="breadcrumbs mb-0">
                    <li class="breadcrumb-item active">{{ __('profile.profile') }}</li>
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">{{ __('profile.home') }}</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="col s12">
    <div class="container">
<div class="row">
    <div class="col s12">
        <div id="input-fields" class="card card-tabs">
            <div class="card-content">
                <!-- <div class="card-title">
                    <div class="row">
                        <div class="col s12 m6 l10">
                            <h4 class="card-title">{{ __('profile.add') }}</h4>
                        </div>
                    </div>
                </div> -->
                <div id="view-input-fields" class="active">
                    <div class="row">
                        <div class="col s12">
                            <div class="col s12">
                                <div class="input-field col s12">
                                    <input value="{{ old('name',$profile->name) }}"id="customer-name" type="text"  readonly />
                                    <label for="customer-name" class="active">{{ __('profile.name') }}</label>
                                </div>

                                <div class="input-field col s12">
                                    <input value="{{ old('email',$profile->email) }}" name="email" id="customer-email" type="text" readonly />
                                    <label for="customer-email" class="active">{{ __('profile.email') }}</label>
                                </div>

                                <div class="input-field col s12">
                                    <input value="{{ $profile->getRoles()->first() }}"  id="profile-role" type="text"  readonly />
                                    <label for="profile-role" class="active">{{ __('profile.role') }}</label>
                                </div>

                                <!-- <div class="input-field col s12 pt-3">
                                  	<a class="btn waves-effect waves-light " href="{{ route('user.edit',[ 'user' => $profile->id ]) }}">{{ __('profile.edit') }}</a>
                                </div> -->
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script src="https://cdn.ckeditor.com/4.10.1/standard/ckeditor.js"></script>
<script>
  $(document).ready(function() {
       
   });
</script>
  
@endsection